#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

pattern="^(chore|docs|feat|test): .+"

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
  echo "❌ Invalid commit message format."
  echo "Expected format: <type>: <message>"
  echo "Allowed types: chore | docs | feat | test"
  echo ""
  echo "Example: feat: add user authentication"
  exit 1
fi